gateSyn = '(gate|door|lock)'
deadSyn = '(woman|soldier|girl|body|deceased|dead|departed|mort|remain|bone|flesh|killed|goner)'
prisonSyn = '(prison|cell|jail|confinement|lockup|penitentiary|bastille|dungeon|bars)'
askSyn = '(ask|help|seek|meet|soldier|confront|fight)'
runSyn = '(run|hide|escape|exit|bounce)'
checkSyn = '(check|inspect|find|look|strip|search|examine)'
